apiVersion: v1
items:
- apiVersion: memsql.com/v1alpha1
  kind: MemsqlCluster
  metadata:
    creationTimestamp: "2023-08-17T13:37:28Z"
    generation: 2
    name: sdb-cluster
    namespace: default
    resourceVersion: "6640559"
    uid: 7e80b873-5b72-4478-b9b4-459db17501e2
  spec:
    adminHashedPassword: '*7EE969BBE0A3985C8BFF9FA65A06345C67FE434A'
    aggregatorSpec:
      count: 2
      height: 0.125
      objectMetaOverrides:
        annotations:
          optional: annotation
        labels:
          optional: label
      storageClass: standard
      storageGB: 10
    leafSpec:
      annotations:
        optional: annotation
      count: 2
      height: 0.125
      labels:
        optional: label
      objectMetaOverrides: null
      storageClass: standard
      storageGB: 10
    license: BDIwNTY2MzczYmQ3ZTQ0OTBhNzgzYjEzYzI2ZjFlMWYwAAAAAAAAAAAAAAAAAAAAAAMwNQIYRaxfeh15wzJd+mHRW78Xv6PGnh1vlSnSAhkAk/Fw+QJCKDeEhFb5ed7DvMhGvijPZrHFAA==
    nodeImage:
      repository: singlestore/node
      tag: alma-8.0.22-5f4a041ae5
    redundancyLevel: 1
    schedulingDetails:
      leaf-ag1:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - ip-172-31-89-145
                  - ip-172-31-92-117
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: sdb-cluster
              topologyKey: kubernetes.io/hostname
      master:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - ip-172-31-82-213
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: sdb-cluster
              topologyKey: kubernetes.io/hostname
    serviceSpec:
      annotations:
        custom: annotations
      labels:
        custom: label
      objectMetaOverrides: null
  status:
    WorkspaceStatus:
      singlestore-central:
        WorkspaceID: ""
        dmlEndpoint: 172.31.82.213:3306
        dmlEndpointState:
          recreation: None
        expectedAggregators: 2
        expectedLeaves: 2
        expectedNodes: 4
        mysqlDMLPort: 3306
        rawDmlEndpoint: 172.31.82.213:3306
        readyNodes: 4
        websocketDMLPort: 0
    clusterInitialized: true
    ddlEndpoint: 172.31.85.245:3306
    ddlEndpointState:
      recreation: None
    dmlEndpoint: 172.31.82.213:3306
    dmlEndpointState:
      recreation: None
    expectedAggregators: 2
    expectedLeaves: 2
    expectedMasters: 1
    expectedNodes: 4
    observedGeneration: 2
    openPorts:
      mysqlDDL: 3306
      mysqlDML: 3306
      websocket: 0
    operatorVersion: 3.0.96
    persistedLoadBalancerIPChanges:
      svc-sdb-cluster: ""
      svc-sdb-cluster-ddl: ""
      svc-sdb-cluster-dml: ""
    phase: Running
    rawDdlEndpoint: 172.31.85.245:3306
    rawDmlEndpoint: 172.31.82.213:3306
    readyNodes: 4
    rebalanceNeeded: false
kind: List
metadata:
  resourceVersion: ""
