---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdb-operator
  labels:
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sdb-operator
  template:
    metadata:
      labels:
        name: sdb-operator
    spec:
      serviceAccountName: sdb-operator
      containers:
        - name: sdb-operator
          image: singlestore/operator:3.0.98-156a0090
          imagePullPolicy: Always
          args:
            - --merge-service-annotations
            - --fs-group-id
            - "5555"
            - --cluster-id
            - sdb-cluster
            - --backup-bucket-name
            - "support"
            - --backup-cloud-service-provider
            - "azure"
            - --backup-endpoint
            - "https://s2support.blob.core.windows.net/support"
            - --backup-default-schedule
            - "27 05 * * *"
            - --backup-secret-name
            - "azure-credential"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: sdb-operator
